/**
 * The brick foundry: build a brand-new brick (optionally backed by a freshly
 * installed npm library) and register it so it becomes "known".
 *
 * POST body: { name, description, tags?, npmPackage?, schemaSource, componentSource }
 *  - schemaSource: a full module exporting `schema` (a zod object) + `Props`.
 *  - componentSource: a full "use client" module exporting `Component`.
 * Steps: validate → (npm install) → write src/bricks/generated/<kebab>/{schema,
 * component,index} → rewrite the generated barrel → persist + embed for search.
 * The dev server hot-reloads, so the brick is immediately usable.
 *
 * Guarded by name/package validation; intended to be reached only after the
 * user approves (or Auto mode is on).
 */
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdir, readdir, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import pgvector from "pgvector/pg";
import { getPool, migrate } from "@/server/db";
import { embed } from "@/server/embeddings";

export const runtime = "nodejs";
export const maxDuration = 180;

const exec = promisify(execFile);
const ROOT = process.cwd();
const GEN_DIR = path.join(ROOT, "src", "bricks", "generated");

const NAME_RE = /^[A-Z][A-Za-z0-9]{1,40}$/;
const PKG_RE = /^(@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*(@[\w.^~>=<-]+)?$/i;

const kebab = (name: string) =>
  name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

interface FoundryBody {
  name?: string;
  description?: string;
  tags?: string[];
  npmPackage?: string;
  schemaSource?: string;
  componentSource?: string;
}

/** Rebuild the generated barrel from whatever brick folders currently exist. */
async function rewriteBarrel() {
  const entries = await readdir(GEN_DIR, { withFileTypes: true });
  const dirs: string[] = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    try {
      await stat(path.join(GEN_DIR, e.name, "index.ts"));
      dirs.push(e.name);
    } catch {
      /* no index.ts — skip */
    }
  }
  const imports = dirs
    .map((d, i) => `import { brick as b${i} } from "./${d}";`)
    .join("\n");
  const list = dirs.map((_, i) => `b${i}`).join(", ");
  const content = `/**
 * AUTO-GENERATED by /api/foundry — do not edit by hand.
 * Barrel of foundry-built bricks; rewritten whenever a brick is created.
 */
import type { BrickDef } from "@/bricks/types";
${imports}

export const GENERATED_BRICKS: BrickDef[] = [${list}];
`;
  await writeFile(path.join(GEN_DIR, "index.ts"), content, "utf8");
}

export async function POST(req: Request) {
  let body: FoundryBody;
  try {
    body = (await req.json()) as FoundryBody;
  } catch {
    return Response.json({ error: "invalid JSON" }, { status: 400 });
  }
  const { name, description, tags = [], npmPackage, schemaSource, componentSource } = body;

  if (!name || !NAME_RE.test(name)) {
    return Response.json({ error: "name must be PascalCase (e.g. NodeGraph)" }, { status: 400 });
  }
  if (!description || !schemaSource || !componentSource) {
    return Response.json(
      { error: "description, schemaSource and componentSource are required" },
      { status: 400 },
    );
  }
  if (npmPackage && !PKG_RE.test(npmPackage)) {
    return Response.json({ error: `unsafe package name: ${npmPackage}` }, { status: 400 });
  }

  let installed: string | null = null;
  if (npmPackage) {
    try {
      await exec("npm", ["install", npmPackage, "--no-audit", "--no-fund", "--save"], {
        cwd: ROOT,
        timeout: 150_000,
        maxBuffer: 1024 * 1024 * 16,
      });
      installed = npmPackage;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return Response.json(
        { error: `npm install ${npmPackage} failed`, detail: msg.slice(0, 500) },
        { status: 502 },
      );
    }
  }

  // Write the three brick files.
  const dir = path.join(GEN_DIR, kebab(name));
  try {
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, "schema.ts"), schemaSource, "utf8");
    await writeFile(path.join(dir, "component.tsx"), componentSource, "utf8");
    const indexSrc = `import { defineBrick } from "@/bricks/types";
import { schema } from "./schema";
import { Component } from "./component";

export const brick = defineBrick({
  name: ${JSON.stringify(name)},
  description: ${JSON.stringify(description)},
  tags: ${JSON.stringify(tags)},
  schema,
  acceptsChildren: false,
  Component,
});
`;
    await writeFile(path.join(dir, "index.ts"), indexSrc, "utf8");
    await rewriteBarrel();
  } catch (err) {
    return Response.json(
      { error: "failed to write brick files", detail: String(err).slice(0, 500) },
      { status: 500 },
    );
  }

  // Persist + embed so the brick is recorded and searchable immediately.
  try {
    await migrate();
    const pool = await getPool();
    await pool.query(
      `INSERT INTO generated_bricks (name, description, tags, npm_package, schema_source, component_source)
       VALUES ($1,$2,$3,$4,$5,$6)
       ON CONFLICT (name) DO UPDATE SET description=EXCLUDED.description, tags=EXCLUDED.tags,
         npm_package=EXCLUDED.npm_package, schema_source=EXCLUDED.schema_source,
         component_source=EXCLUDED.component_source`,
      [name, description, tags, npmPackage ?? null, schemaSource, componentSource],
    );
    const vector = await embed(`${name}: ${description} (tags: ${tags.join(", ")})`);
    await pool.query(
      `INSERT INTO bricks (name, description, tags, embedding)
       VALUES ($1,$2,$3,$4::vector)
       ON CONFLICT (name) DO UPDATE SET description=EXCLUDED.description,
         tags=EXCLUDED.tags, embedding=EXCLUDED.embedding`,
      [name, description, tags, pgvector.toSql(vector)],
    );
  } catch (err) {
    // Files are written; persistence/search is best-effort.
    return Response.json({ ok: true, name, installed, warn: String(err).slice(0, 300) });
  }

  return Response.json({ ok: true, name, installed });
}
