/**
 * The brick foundry: build a brand-new brick (optionally backed by a freshly
 * installed npm library) and register it so it becomes "known".
 *
 * Async by design: POST validates + kicks off a background job (npm install can
 * take a while) and returns a jobId immediately; clients poll GET ?jobId=… for
 * the result. Steps: (npm install) → write src/bricks/generated/<kebab>/{schema,
 * component,index} → rewrite the generated barrel → persist + embed for search.
 * The dev server hot-reloads, so the brick is immediately usable.
 */
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdir, readdir, writeFile, stat } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import path from "node:path";
import pgvector from "pgvector/pg";
import { getPool, migrate } from "@/server/db";
import { embed } from "@/server/embeddings";

export const runtime = "nodejs";
export const maxDuration = 300;

const exec = promisify(execFile);
const ROOT = process.cwd();
const GEN_DIR = path.join(ROOT, "src", "bricks", "generated");

const NAME_RE = /^[A-Z][A-Za-z0-9]{1,40}$/;
const PKG_RE = /^(@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*(@[\w.^~>=<-]+)?$/i;

const kebab = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

interface FoundryBody {
  name?: string;
  description?: string;
  tags?: string[];
  npmPackage?: string;
  schemaSource?: string;
  componentSource?: string;
}

interface Job {
  status: "running" | "done" | "error";
  name: string;
  installed: string | null;
  message?: string;
  detail?: string;
}

// Module-scoped job registry (persists across requests in the dev server process).
const jobs = new Map<string, Job>();

async function rewriteBarrel() {
  const entries = await readdir(GEN_DIR, { withFileTypes: true });
  const dirs: string[] = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    try {
      await stat(path.join(GEN_DIR, e.name, "index.ts"));
      dirs.push(e.name);
    } catch {
      /* skip */
    }
  }
  const imports = dirs.map((d, i) => `import { brick as b${i} } from "./${d}";`).join("\n");
  const list = dirs.map((_, i) => `b${i}`).join(", ");
  await writeFile(
    path.join(GEN_DIR, "index.ts"),
    `/**\n * AUTO-GENERATED by /api/foundry — do not edit by hand.\n */\nimport type { BrickDef } from "@/bricks/types";\n${imports}\n\nexport const GENERATED_BRICKS: BrickDef[] = [${list}];\n`,
    "utf8",
  );
}

/** The actual build work — run in the background; updates the job entry. */
async function runFoundry(jobId: string, body: Required<Pick<FoundryBody, "name" | "description" | "schemaSource" | "componentSource">> & FoundryBody) {
  const { name, description, tags = [], npmPackage, schemaSource, componentSource } = body;
  try {
    let installed: string | null = null;
    if (npmPackage) {
      await exec("npm", ["install", npmPackage, "--no-audit", "--no-fund", "--save"], {
        cwd: ROOT,
        timeout: 240_000,
        maxBuffer: 1024 * 1024 * 16,
      });
      installed = npmPackage;
    }
    jobs.set(jobId, { status: "running", name, installed });

    const dir = path.join(GEN_DIR, kebab(name));
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, "schema.ts"), schemaSource, "utf8");
    await writeFile(path.join(dir, "component.tsx"), componentSource, "utf8");
    await writeFile(
      path.join(dir, "index.ts"),
      `import { defineBrick } from "@/bricks/types";\nimport { schema } from "./schema";\nimport { Component } from "./component";\n\nexport const brick = defineBrick({\n  name: ${JSON.stringify(name)},\n  description: ${JSON.stringify(description)},\n  tags: ${JSON.stringify(tags)},\n  schema,\n  acceptsChildren: false,\n  Component,\n});\n`,
      "utf8",
    );
    await rewriteBarrel();

    try {
      await migrate();
      const pool = await getPool();
      await pool.query(
        `INSERT INTO generated_bricks (name, description, tags, npm_package, schema_source, component_source)
         VALUES ($1,$2,$3,$4,$5,$6)
         ON CONFLICT (name) DO UPDATE SET description=EXCLUDED.description, tags=EXCLUDED.tags,
           npm_package=EXCLUDED.npm_package, schema_source=EXCLUDED.schema_source,
           component_source=EXCLUDED.component_source`,
        [name, description, tags, npmPackage ?? null, schemaSource, componentSource],
      );
      const vector = await embed(`${name}: ${description} (tags: ${tags.join(", ")})`);
      await pool.query(
        `INSERT INTO bricks (name, description, tags, embedding) VALUES ($1,$2,$3,$4::vector)
         ON CONFLICT (name) DO UPDATE SET description=EXCLUDED.description, tags=EXCLUDED.tags, embedding=EXCLUDED.embedding`,
        [name, description, tags, pgvector.toSql(vector)],
      );
    } catch {
      /* persistence/search is best-effort; files are written */
    }

    jobs.set(jobId, {
      status: "done",
      name,
      installed,
      message: `Created "${name}"${installed ? ` (installed ${installed})` : ""}.`,
    });
  } catch (err) {
    jobs.set(jobId, {
      status: "error",
      name,
      installed: null,
      message: npmPackage ? `npm install ${npmPackage} failed` : "build failed",
      detail: String(err).slice(0, 500),
    });
  }
}

export async function POST(req: Request) {
  let body: FoundryBody;
  try {
    body = (await req.json()) as FoundryBody;
  } catch {
    return Response.json({ error: "invalid JSON" }, { status: 400 });
  }
  const { name, description, npmPackage, schemaSource, componentSource } = body;
  if (!name || !NAME_RE.test(name)) {
    return Response.json({ error: "name must be PascalCase (e.g. NodeGraph)" }, { status: 400 });
  }
  if (!description || !schemaSource || !componentSource) {
    return Response.json({ error: "description, schemaSource and componentSource are required" }, { status: 400 });
  }
  if (npmPackage && !PKG_RE.test(npmPackage)) {
    return Response.json({ error: `unsafe package name: ${npmPackage}` }, { status: 400 });
  }

  const jobId = randomUUID();
  jobs.set(jobId, { status: "running", name, installed: null });
  // Fire-and-forget: build in the background, return the job handle now.
  void runFoundry(jobId, body as Parameters<typeof runFoundry>[1]);
  return Response.json({ ok: true, jobId, status: "running" });
}

export async function GET(req: Request) {
  const jobId = new URL(req.url).searchParams.get("jobId");
  if (!jobId) return Response.json({ error: "jobId required" }, { status: 400 });
  const job = jobs.get(jobId);
  if (!job) return Response.json({ status: "unknown" });
  return Response.json(job);
}
