"use client";

/**
 * Export the current report as JSON (re-importable), standalone HTML, React/TSX,
 * PNG, or PDF — plus Import JSON. Snapshots (HTML/PNG/PDF) capture the rendered
 * canvas surface; live feeds / WebGL maps are frozen in those formats.
 */
import * as React from "react";
import * as Y from "yjs";
import type { CompositionNode } from "@/bricks/composition";
import { getActiveDoc } from "@/engine/doc-registry";
import { buildReportBundle, bytesToBase64 } from "@/export/pwa";
import { Download } from "lucide-react";
import { collectDocumentCss } from "@/export/collect-css";
import { bakeToBrick, toPascalBrickName } from "@/export/bake";
import { MenuButton } from "@/components/ui/MenuButton";

const THEME_VARS = [
  "--background", "--foreground", "--card", "--card-foreground", "--primary",
  "--primary-foreground", "--secondary", "--secondary-foreground", "--muted",
  "--muted-foreground", "--border", "--input", "--ring", "--radius",
];

function download(name: string, data: string | Blob, type = "text/plain") {
  const blob = typeof data === "string" ? new Blob([data], { type }) : data;
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Generate readable JSX for the composition (references the brick components). */
function toJsx(node: CompositionNode, indent = 1): string {
  const pad = "  ".repeat(indent);
  const props = Object.entries(node.props ?? {})
    .map(([k, v]) =>
      typeof v === "string" ? `${k}=${JSON.stringify(v)}` : `${k}={${JSON.stringify(v)}}`,
    )
    .join(" ");
  const head = `${node.brick}${props ? " " + props : ""}`;
  if (node.children?.length) {
    return `${pad}<${head}>\n${node.children.map((c) => toJsx(c, indent + 1)).join("\n")}\n${pad}</${node.brick}>`;
  }
  return `${pad}<${head} />`;
}

function surfaceEl(): HTMLElement | null {
  return document.querySelector(".widget-surface");
}

export function ExportMenu({
  widget,
  onImport,
}: {
  widget: CompositionNode | null;
  onImport: (tree: unknown) => void;
}) {
  const [open, setOpen] = React.useState(false);
  const fileRef = React.useRef<HTMLInputElement>(null);

  const exportJson = () => widget && download("report.json", JSON.stringify(widget, null, 2), "application/json");

  const exportReact = () => {
    if (!widget) return;
    const src = `// Generated by london-A2UI. Uses the brick component library.\nexport default function Report() {\n  return (\n${toJsx(widget, 2)}\n  );\n}\n`;
    download("Report.tsx", src, "text/plain");
  };

  const exportHtml = () => {
    const el = surfaceEl();
    if (!el) return;
    const cs = getComputedStyle(document.documentElement);
    const vars = THEME_VARS.map((v) => `      ${v}: ${cs.getPropertyValue(v).trim()};`).join("\n");
    // Inline the app's REAL compiled CSS so it's fully styled offline (no CDN).
    const css = collectDocumentCss();
    const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>Report</title>
<style>${css}</style>
<style>:root{\n${vars}\n}body{background:var(--background);color:var(--foreground);font-family:Inter,system-ui,Arial,sans-serif;padding:24px}</style>
</head><body>${el.innerHTML}</body></html>`;
    download("site.html", html, "text/html");
  };

  const bake = async () => {
    if (!widget) return;
    const raw = window.prompt("Name this brick — it'll appear in the palette + for the agent:", "MySection");
    if (!raw) return;
    try {
      const msg = await bakeToBrick(toPascalBrickName(raw), widget);
      window.alert(msg);
    } catch (e) {
      window.alert(`Bake failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  };

  const exportPwa = () => {
    const el = surfaceEl();
    if (!el) return;
    const cs = getComputedStyle(document.documentElement);
    const themeCss = THEME_VARS.map((v) => `  ${v}: ${cs.getPropertyValue(v).trim()};`).join("\n");
    const doc = getActiveDoc();
    const stateUpdateB64 = doc ? bytesToBase64(Y.encodeStateAsUpdate(doc)) : "";
    const html = buildReportBundle({
      title: "A2UI Site",
      bodyHtml: el.innerHTML,
      themeCss,
      css: collectDocumentCss(), // REAL compiled CSS → styled offline / installed
      tree: widget,
      stateUpdateB64,
    });
    download("site.html", html, "text/html");
  };

  const exportPng = async () => {
    const el = surfaceEl();
    if (!el) return;
    const { toPng } = await import("html-to-image");
    const dataUrl = await toPng(el, { backgroundColor: getComputedStyle(document.documentElement).getPropertyValue("--background") || "#fff", pixelRatio: 2 });
    const res = await fetch(dataUrl);
    download("report.png", await res.blob(), "image/png");
  };

  const exportPdf = async () => {
    const el = surfaceEl();
    if (!el) return;
    const { toPng } = await import("html-to-image");
    const { jsPDF } = await import("jspdf");
    const dataUrl = await toPng(el, { pixelRatio: 2, backgroundColor: "#ffffff" });
    const img = new Image();
    img.src = dataUrl;
    await new Promise((r) => (img.onload = r));
    const pdf = new jsPDF({ orientation: img.width > img.height ? "l" : "p", unit: "px", format: [img.width, img.height] });
    pdf.addImage(dataUrl, "PNG", 0, 0, img.width, img.height);
    pdf.save("report.pdf");
  };

  const onFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    try {
      onImport(JSON.parse(await file.text()));
    } catch {
      /* ignore bad file */
    }
    e.target.value = "";
    setOpen(false);
  };

  const Item = ({ label, onClick }: { label: string; onClick: () => void }) => (
    <button
      onClick={() => {
        onClick();
        setOpen(false);
      }}
      className="w-full rounded-[var(--radius)] px-2 py-1.5 text-left text-sm hover:bg-[var(--secondary)]"
    >
      {label}
    </button>
  );

  return (
    <div className="relative">
      <MenuButton
        icon={Download}
        label="Export"
        active={open}
        onClick={() => setOpen((o) => !o)}
        title="Bake to brick, export the site (HTML/PWA/React/PNG/PDF), or import"
      />
      {open && (
        <div className="absolute right-0 z-50 mt-1 flex w-44 flex-col rounded-[var(--radius)] border border-[var(--border)] bg-[var(--card)] p-1 shadow-md">
          <Item label="🧱 Bake to brick…" onClick={() => void bake()} />
          <div className="my-1 border-t border-[var(--border)]" />
          <Item label="Download JSON" onClick={exportJson} />
          <Item label="Import JSON…" onClick={() => fileRef.current?.click()} />
          <div className="my-1 border-t border-[var(--border)]" />
          <Item label="Standalone site (HTML)" onClick={exportHtml} />
          <Item label="Runnable site (offline PWA)" onClick={exportPwa} />
          <Item label="React (.tsx)" onClick={exportReact} />
          <Item label="PNG image" onClick={() => void exportPng()} />
          <Item label="PDF" onClick={() => void exportPdf()} />
        </div>
      )}
      <input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={onFile} />
    </div>
  );
}
